export interface FootfallEntry {
  name: string;
  age: number;
  city: string;
}

export const FOOTFALL_BY_REGION: Record<string, FootfallEntry[]> = {
  IN: [
    { name: "Priya", age: 28, city: "Mumbai" },
    { name: "Aanya", age: 31, city: "Delhi" },
    { name: "Meera", age: 26, city: "Bangalore" },
    { name: "Ishaan", age: 34, city: "Pune" },
    { name: "Rhea", age: 29, city: "Hyderabad" },
    { name: "Kavya", age: 27, city: "Chennai" },
    { name: "Aryan", age: 33, city: "Mumbai" },
    { name: "Sanya", age: 30, city: "Gurgaon" },
    { name: "Divya", age: 25, city: "Bangalore" },
    { name: "Rohan", age: 32, city: "Kolkata" },
    { name: "Nisha", age: 28, city: "Jaipur" },
    { name: "Vivaan", age: 35, city: "Mumbai" },
    { name: "Ananya", age: 27, city: "Delhi" },
    { name: "Kabir", age: 31, city: "Chandigarh" },
    { name: "Tara", age: 29, city: "Ahmedabad" },
  ],
  NP: [
    { name: "Sunita", age: 27, city: "Kathmandu" },
    { name: "Aashish", age: 30, city: "Pokhara" },
    { name: "Nisha", age: 26, city: "Kathmandu" },
    { name: "Prashant", age: 33, city: "Lalitpur" },
    { name: "Sujata", age: 28, city: "Biratnagar" },
  ],
  PK: [
    { name: "Fatima", age: 27, city: "Karachi" },
    { name: "Ahmed", age: 31, city: "Lahore" },
    { name: "Zara", age: 26, city: "Islamabad" },
    { name: "Hassan", age: 33, city: "Karachi" },
    { name: "Aisha", age: 29, city: "Lahore" },
  ],
  US: [
    { name: "Sophia", age: 27, city: "New York" },
    { name: "Alexandra", age: 32, city: "Los Angeles" },
    { name: "James", age: 34, city: "Chicago" },
    { name: "Emma", age: 29, city: "San Francisco" },
    { name: "Oliver", age: 31, city: "Miami" },
    { name: "Isabella", age: 28, city: "New York" },
    { name: "Liam", age: 35, city: "Boston" },
    { name: "Ava", age: 26, city: "Austin" },
    { name: "Noah", age: 33, city: "Seattle" },
    { name: "Mia", age: 30, city: "Nashville" },
    { name: "Ethan", age: 28, city: "Denver" },
    { name: "Charlotte", age: 31, city: "Atlanta" },
  ],
  GB: [
    { name: "Olivia", age: 28, city: "London" },
    { name: "Harry", age: 32, city: "London" },
    { name: "Isla", age: 26, city: "Edinburgh" },
    { name: "George", age: 33, city: "Manchester" },
    { name: "Amelia", age: 29, city: "London" },
    { name: "Jack", age: 31, city: "Bristol" },
  ],
  AE: [
    { name: "Layla", age: 27, city: "Dubai" },
    { name: "Omar", age: 31, city: "Dubai" },
    { name: "Nour", age: 26, city: "Abu Dhabi" },
    { name: "Khalid", age: 34, city: "Dubai" },
    { name: "Yasmin", age: 29, city: "Dubai" },
  ],
  SG: [
    { name: "Mei", age: 27, city: "Singapore" },
    { name: "Arjun", age: 30, city: "Singapore" },
    { name: "Jing", age: 26, city: "Singapore" },
    { name: "Wei", age: 32, city: "Singapore" },
    { name: "Priya", age: 28, city: "Singapore" },
  ],
  AU: [
    { name: "Charlotte", age: 28, city: "Sydney" },
    { name: "Liam", age: 31, city: "Melbourne" },
    { name: "Ava", age: 26, city: "Brisbane" },
    { name: "Noah", age: 33, city: "Perth" },
    { name: "Mia", age: 29, city: "Sydney" },
  ],
  DEFAULT: [
    { name: "Sophia", age: 27, city: "New York" },
    { name: "James", age: 32, city: "London" },
    { name: "Layla", age: 26, city: "Dubai" },
    { name: "Oliver", age: 34, city: "Paris" },
    { name: "Mei", age: 28, city: "Singapore" },
    { name: "Aanya", age: 31, city: "Mumbai" },
    { name: "Charlotte", age: 29, city: "Sydney" },
    { name: "Arjun", age: 33, city: "Toronto" },
    { name: "Isabelle", age: 27, city: "Amsterdam" },
    { name: "Luca", age: 30, city: "Milan" },
    { name: "Zara", age: 28, city: "Tokyo" },
    { name: "Rafael", age: 32, city: "São Paulo" },
  ],
};
