-- AI review result stored per mommy application
ALTER TABLE public.mommy_applications
  ADD COLUMN IF NOT EXISTS ai_review JSONB;

COMMENT ON COLUMN public.mommy_applications.ai_review IS
  'Gemini AI review: { quality_score, strengths, red_flags, suggested_tags, admin_summary }';

-- Personalized match intro generated by Gemini during the nightly cron
ALTER TABLE public.matches
  ADD COLUMN IF NOT EXISTS match_intro TEXT;

COMMENT ON COLUMN public.matches.match_intro IS
  'AI-generated 1-2 sentence intro shown to the member on their match card. Null if generation failed or skipped.';
